main="./worker/index.js"
name = "vite-ssr-dynamic"
compatibility_flags = []
compatibility_date = "2023-03-14"
workers_dev = true
node_compat = true

[site]
bucket = "./dist/client"

[dev]
port = 3000
